### PR TITLE
Implement GitHub Actions (maven and updater/version checking)

### PR DESCRIPTION
**Pull request by SpraxDev**
Thanks to @jlsjonas for the idea (https://github.com/BlackScarx/BetterChairs/pull/13) to use GitHub Pages to provide the current plugin version. I'll write some GitHub Actions to make sure the versions in `pom.xml` and `docs/version.txt` are identical

### CODE REVIEW

**Comment by jlsjonas** [comment]
@Sprax2013 You're welcome
Is this the _new_ repo? as I see my PR is still open on BlackScarX's one (and there's quite some commit activity here in comparison)

**Comment by SpraxDev** [comment]
> @Sprax2013 You're welcome
> Is this the _new_ repo? as I see my PR is still open on BlackScarX's one (and there's quite some commit activity here in comparison)

I once received write permissions on the original repository after contacting the author on SpigotMC. He never replied to me or told he would give it to me. So I'm not sure if it was an accident.
Because he didn't reply and got a bit bored, I saw some community activity on the repository and wanted to make things easier for the original author by reviewing PRs etc.
I can't even update the page on SpigotMC so I didn't really bother merging myself to update the Plugin, as I can't really provide it to people.

And so I just forked it, rewrote to use Maven because the old system just kind of bad and illegal (uploading spigot binaries to the public) and setup some CI.

I contacted the original author again trying to continue the Project in his place with this repository.

I won't merge the latest version to the original repository as I had to rewrite all the commits to entirely remove the spigot binaries from git history... So I would need to force-push instead of just archiving the repository or something like that.

I'll also do a complete recode keeping the old API intact via abstraction etc. because I just don't like the coding style and it would get hard for me to maintain this code.

If he doesn't reply as he has been inactive for a couple of months now I think, I'll just create a new Plugin on SpigotMC with proper credits and all so we can enjoy an up-to-date version of it.

I'm of cours open for opinions, issues and everything else

// Edit: rewriting git history is the reason why my repository is 21 commits behind. The hashes changed

**Comment by jlsjonas** [comment]
> because the old system just kind of bad and illegal

I noticed that too, thought long before actually committing... (and had to work out some mess :joy: )

In this case I'd also be in favor of just releasing it under a new plugin (even though, if I remember correctly something was mentioned on his original page about that... but several months notice & the fact that you had to rewrite it significantly should warrant that imho.

If future changes would be needed you can count me in to help update & maintain it.

**Comment by SpraxDev** [comment]
The only thing that I mostly copied are the NMS classes and BetterChairs is not the first Chairs plugin... So yeah, it is compatible with the old config etc. but the plugin is fully rewritten. Plus I have write access to the repo, so I am kind of part of the project, I guess? xD

Well at least having write-access gave me the freedom to just report my dev build to [bStats](https://bstats.org/plugin/bukkit/BetterChairs/768) as v0.11.0 (Shows up sometimes when testing).

But if he doesn't respond, I'll just create a new SpigotMC plugin giving him the credits for the original plugin but continuing *my own journey*, I guess.

I think the last thing that just needs to be done is copying and testing NMS code for the missing versions as the method names for setting NBT data change between version. Config should be done on my local repo I thing 🤔
Do you have a (public?) server that could be used for testing?

**Comment by jlsjonas** [comment]
I maintain a public server yes, I could set up a demo area or world for the purposes of the plugin.

**Comment by SpraxDev** [comment]
Current status and new version in #15. Would be great, if you could test it :)

`config.yml` is copied/renamed and a new one is created (currently not converting old settings into new one)

**Pull request merged**
